### ISSUE TITLE
If there's no WG

### ISSUE THREAD

**Issue by becarpenter** [ietf/www.ietf.org#10]
This seems incomplete. A missing option is taking a draft to the Area WG when there is one (intarea, opsawg, rtgwg, tsvwg), and there are already three DISPATCH WGs; it's by no means certain that ALLDISPATCH will work at all.

https://github.com/ietf/www.ietf.org/blob/d6d3ef8df9728348d0102ed4c465c176e42f759f/Guide%20to%20bringing%20new%20work%20to%20the%20IETF.md?plain=1#L48

**Comment by JayDaley** [comment]
Now added a bullet about that.
