### ISSUE TITLE
Share??

### ISSUE THREAD

**Issue by becarpenter** [ietf/www.ietf.org#11]
"Almost everything you write and share with the IETF" is IMHO vague, because I don't know what "share" means in the context. Certainly, reading the BCP, anything you _say_ is a contribution, as well as anything you write. And there's a complicated question about whether a bar conversation at an IETF meeting site is private or not. I'm not sure I have a text proposal but I am sure that the text needs clarification.

https://github.com/ietf/www.ietf.org/blob/d6d3ef8df9728348d0102ed4c465c176e42f759f/Guide%20to%20Intellectual%20Property%20Rights%20and%20the%20IETF.md?plain=1#L17

**Comment by JayDaley** [comment]
Fixed with new text
`Almost everything you provide to the IETF, as set out below, is classified as`
