### ISSUE TITLE
404 page has a link to an obsoleted RFC

### ISSUE THREAD

**Issue by cindymorgan** [ietf/www.ietf.org#17]
From: 	"Alice Russo" <arusso@amsl.com>
Subject: 	the 404 page has a link to an obsoleted RFC
Date: 	Wed, 19 Jun 2024 15:27:21 -0700
To: 	support@ietf.org

https://www.ietf.org/404.html 
contains

    Did you know that the IETF is where the [404 error code](https://www.ietf.org/rfc/rfc7231.txt) is defined?

which links to https://www.ietf.org/rfc/rfc7231.txt

Seemingly should be
https://www.ietf.org/rfc/rfc9110.txt
or better yet the HTML --
https://www.ietf.org/rfc/rfc9110.html 

because RFC 7231 was obsoleted by RFC 9110 in June 2022.

Thanks,
Alice

**Comment by rjsparks** [comment]
cc: @ghwood

**Comment by ghwood** [comment]
I think @kesara has to handle this?

**Comment by kesara** [comment]
@ghwood Yes. This is in wagtail source [^1].

[^1]: https://github.com/ietf-tools/www/blob/313e25da0198564b1a76390b60575b2685eac6aa/ietf/templates/404.html

**Comment by kesara** [comment]
--removed: incorrect statement--

**Comment by cindymorgan** [comment]
https://www.staging.ietf.org/404/ <https://www.staging.ietf.org/404/> still has the wrong link for "Did you know that the IETF is where the 404 error code <https://www.ietf.org/rfc/rfc7231.txt> is defined?" It should point to https://www.ietf.org/rfc/rfc9110.html instead of https://www.ietf.org/rfc/rfc7231.txt

**Comment by rjsparks** [comment]
The code has been corrected, but the correction has not yet been deployed. It will be deployed to production as part of today's outage. It may not make it to staging before then (because of the NZ timezone difference).

**Comment by kesara** [comment]
This change will be part of today's migration. The updated 404 page is available here: https://www.staging.ietf.org/404/

**Comment by kesara** [comment]
Changes are live now: https://www.ietf.org/cake/
